### ISSUE TITLE
Metadata 4.5 - Database/ElasticSearch/Lupo - migration phase

### ISSUE THREAD

**Issue by svogt0511** [datacite/lupo#1005]
RESOURCES

- [Metadata Schema Release 4.5 Product Spec](https://docs.google.com/document/d/1DC3SJw0W2bdJQeZAbmpbBbNVgJw5Zgq4HRn4ciIQmEI/edit?usp=sharing)
- [Metadata 4.5 - Technical Spec](https://docs.google.com/document/d/1-NW1Ik_2mFFFcy_keduiZe6DjmuyccSLe-4PD4EqXiM/edit?usp=sharing)
- [UPDATED LUPO 4.5 PLAN](https://docs.google.com/document/d/1B8RJWUHsQgeWC207yr-wzMI8V0C3p5MQdkIZKjpZ3Tc/edit?usp=sharing)

This development task includes making DB/ElasticSearch/Lupo mods to allow initial processing of the new publisher_v4 field while maintaining the old field, migrating all DOIs to the new field, then  cleaning up code and unused resources.

MIGRATION TASKS:

- [x] Add rails DB migrate script for new column for publisher obj, using the departure gem. (Issue https://github.com/datacite/lupo/issues/1037)
- [x] Background scripts to populate publisher_obj field for old DOIS. (Issue https://github.com/datacite/lupo/issues/1035)
- [x] Elastic Search mapping - for the publisher_obj field. (Issue https://github.com/datacite/lupo/issues/1020)
- [x] Lupo create/update/get endpoints including (Issues: https://github.com/datacite/lupo/issues/1009, https://github.com/datacite/lupo/issues/1010, https://github.com/datacite/lupo/issues/1011)
    - [x] Lupo logic to write to both fields on create/update.
    - [x] Lupo logic to handle publisher=true/false and get the correct data on get request - to maintain backward compatibility.
    - [x] Lupo logic to handle serializer.
- [x] Lupo activities endpoints - handle new publisher field, maintain backward compatibility. (Issue https://github.com/datacite/lupo/issues/1038)
- [x] openapi.yml updates (Cody - https://github.com/datacite/lupo/pull/1048) - waiting on review.
- [x] Database migration - run the migration scripts for adding and populating the new column - staging/test/production. (Issue https://github.com/datacite/lupo/issues/1039) Will finish this after the first Lupo schema 4.5 release (v5.6)
- [x] ElasticSearch migration - add new template for the new field, run the ES re-index in staging/test/production (https://github.com/datacite/lupo/issues/1040)

TESTING
- [x] Appropriate tests for each endpoint - create/read/update/get/activities
- [x] Test that the new values are treated appropriately (graphql testing https://github.com/datacite/lupo/issues/1013)
